### PR TITLE
Update README to correct syntax for autofill

### PR DESCRIPTION
**Pull request by techdaddies-kevin**

### CODE REVIEW

**Review by marcuschristiansen — COMMENTED** [review]
Does that work? I still get

> [Vue warn]: Failed to resolve directive: place-autofill

**Comment by techdaddies-kevin** [comment]
It definitely worked for me.

**Comment by marcuschristiansen** [comment]
I'm getting 

> Failed to resolve directive: place-autofill

**Comment by 2PacIsAlive** [comment]
+1 :)

**Pull request merged**
